site_name: Example Project
site_url: https://xxx
repo_url: https://xxx
repo_name: example/project
edit_uri: edit/main/docs
site_author: Jacek Galowicz
copyright: Jacek Galowicz

markdown_extensions:
  - admonition
  - meta
  - plantuml_markdown
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

plugins:
    - search
    - with-pdf:
        cover: true
        back_cover: true
        cover_title: Example Project
        cover_subtitle: Project Documentation
        custom_template_path: templates
        output_path: documentation.pdf
        enabled_if_env: ENABLE_PDF_EXPORT
